import "server-only";
import { DISCLOSURE_CATEGORIES, disclosureStatus, disclosureOutcome, type DisclosureView } from "./disclosures";
const escape = (value: string | number) => String(value).replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);

/** Call only after disclosureView admission and integrity checks. Draft answers never enter the export. */
export function disclosureRecord(view: DisclosureView) {
  return { schema: 1, exportedAt: new Date().toISOString(), request: view.request, events: view.events };
}
export function disclosureRecordHtml(view: DisclosureView) {
  const request = view.request;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Restricted PGPZ disclosure record</title><style>body{font:16px/1.6 system-ui,sans-serif;max-width:900px;margin:40px auto;padding:24px;color:#102627}h1,h2,h3{line-height:1.2}section{border-top:1px solid #ccc;margin-top:28px;padding-top:16px}p{white-space:pre-wrap;overflow-wrap:anywhere}small{overflow-wrap:anywhere}button{padding:10px 16px}@media print{button{display:none}section{break-inside:avoid}body{margin:0}}</style></head><body><h1>PGPZ individual disclosure record</h1><p>Restricted • ${escape(request.subject.name)} • ${request.year} • ${escape(request.kind)}</p><p>Request ${escape(request.id)}. Current signed revision: ${request.revision}. Review status: ${escape(disclosureStatus(request.status))}.</p><p>This record contains individual disclosures and review notes. It does not approve a transaction or constitute a Board resolution.</p>${view.events.map((event) => event.kind === "submission" ? `<section><h2>Signed revision ${event.revision}</h2><p>Policy: ${escape(event.policy.title)} • version ${event.policy.sequence} • ${escape(event.policy.adoption)}</p><small>Policy version ID: ${escape(event.policy.versionId)}<br>Policy SHA-256: ${escape(event.policy.sha256)}</small><p>Roles: ${escape(event.form.roles)}</p><p>${escape(event.form.matter)}</p>${event.form.answers.map((answer, index) => `<h3>${index + 1}. ${escape((event.questions ?? DISCLOSURE_CATEGORIES)[index])}</h3><p>${answer.choice === "none" ? "None" : escape(answer.details)}</p>`).join("")}<p>${escape(event.acknowledgment)}</p><p>${escape(event.electronicConsent)}</p><p>Signed and delivered by ${escape(event.signedName)} (${escape(event.actor.email)}) at ${escape(event.deliveredAt)}.</p><small>Authenticated user: ${escape(event.actor.userId)}<br>Record SHA-256: ${escape(event.hash)}<br>Previous signed record: ${escape(event.previousHash ?? "None")}</small></section>` : `<section><h2>${escape(event.kind)} • revision ${event.revision}</h2><p>${escape(event.actor.name)} • ${escape(event.at)} • ${escape(disclosureOutcome(event.outcome))}</p><p>${escape(event.note)}</p></section>`).join("")}<p>Keep this record within the authorized disclosure review group. Use your browser’s Print command to save a PDF.</p></body></html>`;
}
